{{- $svcs := (include "groundx.golang.services" . | fromYaml) -}}
{{- $username := include "groundx.container.username" . -}}

{{- range $idx, $entry := $svcs }}
{{- $svcKey := printf "groundx.%s.settings" $entry -}}
{{- $svcData := include $svcKey $ | fromYaml -}}

{{- $aff := get $svcData "affinity" -}}
{{- $anns := get $svcData "annotations" -}}
{{- $csct := get $svcData "containerSecurityContext" -}}
{{- $dpnd := get $svcData "dependencies" | default dict -}}
{{- $image := get $svcData "image" -}}
{{- $ips := include "groundx.imagePullSecrets" $ | fromYaml -}}
{{- $io := include "groundx.ingestOnly" $ -}}
{{- $lbls := get $svcData "labels" -}}
{{- $int := get $svcData "interface" -}}
{{- $svc := get $svcData "name" -}}
{{- $node := get $svcData "node" -}}
{{- $nsl := get $svcData "nodeSelector" -}}
{{- $cport := get $svcData "port" -}}
{{- $pull := get $svcData "pull" -}}
{{- $rp := get $svcData "replicas" -}}
{{- $rs := get $svcData "resources" -}}
{{- $san := get $svcData "serviceAccountName" -}}
{{- $scr := include "groundx.secrets" $ | fromYaml | default dict -}}
{{- $sct := get $svcData "securityContext" -}}
{{- $tl := get $svcData "tolerations" -}}

{{- $desired := get $rp "desired" -}}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $svc }}
  namespace: {{ include "groundx.ns" $ | quote }}
  labels:
{{ include "groundx.renderDefaultLabels" (dict "name" $svc "indent" 4 "root" $) }}
spec:
  replicas: {{ $desired }}
  selector:
    matchLabels:
      app: {{ $svc }}
  template:
    metadata:
      labels:
        app: {{ $svc }}
{{- if gt (len $lbls) 0 }}
{{ toYaml $lbls | nindent 8 }}
{{- end }}
      annotations:
        config-hash: {{ include (print $.Template.BasePath "/resources/config-yaml.yaml") $ | sha256sum }}
{{- if gt (len $anns) 0 }}
{{ toYaml $anns | nindent 8 }}
{{- end }}
    spec:
{{- if $san }}
      serviceAccountName: {{ $san }}
{{- end }}
{{- if gt (len $ips) 0 }}
      imagePullSecrets:
{{- range $j, $inm := $ips }}
        - name: {{ $inm }}
{{- end }}
{{- end }}
{{- include "groundx.renderAffinity" (dict "ctx" $aff "node" $node "indent" 6 "root" $) }}
{{ include "groundx.renderSecurityContext" (dict "ctx" $sct "indent" 6 "root" $ "user" $username "cfg" "spec") }}
{{ include "groundx.renderNodeSelector" (dict "ctx" $nsl "node" $node "indent" 6 "root" $) }}
{{ include "groundx.renderTolerations" (dict "ctx" $tl "node" $node "indent" 6 "root" $) }}
{{- if not (empty $dpnd) }}
      initContainers:
{{- if hasKey $dpnd "metrics" }}
        - name: wait-for-metrics
          image: {{ include "groundx.busybox.image" $ }}
          imagePullPolicy: {{ include "groundx.busybox.pull" $ | quote }}
          command: ['sh', '-c', "until wget -T 5 -qO- {{ include "groundx.metrics.serviceUrl" $ }}/health; do echo waiting for metrics; sleep 2; done"]
{{- end }}
{{- if hasKey $dpnd "groundx" }}
        - name: wait-for-groundx
          image: {{ include "groundx.busybox.image" $ }}
          imagePullPolicy: {{ include "groundx.busybox.pull" $ | quote }}
          command: ['sh', '-c', "until wget -T 5 -qO- {{ include "groundx.groundx.serviceUrl" $ }}/health; do echo waiting for groundx; sleep 2; done"]
{{- end }}
{{- if hasKey $dpnd "cache" }}
        - name: wait-for-cache
          image: {{ include "groundx.busybox.image" $ }}
          imagePullPolicy: {{ include "groundx.busybox.pull" $ | quote }}
          command: ['sh', '-c', "until nc -z {{ printf "%s %v" (include "groundx.cache.addr" $) (include "groundx.cache.port" $) }}; do echo waiting for cache; sleep 2; done"]
{{- end }}
{{- if hasKey $dpnd "file" }}
        - name: wait-for-file-storage
          image: {{ include "groundx.busybox.image" $ }}
          imagePullPolicy: {{ include "groundx.busybox.pull" $ | quote }}
          command: ['sh', '-c', "until nc -z {{ printf "%s %v" (include "groundx.file.serviceDependency" $) (include "groundx.file.port" $) }}; do echo waiting for file storage; sleep 2; done"]
{{- end }}
{{- if hasKey $dpnd "search" }}
        - name: wait-for-search
          image: {{ include "groundx.busybox.image" $ }}
          imagePullPolicy: {{ include "groundx.busybox.pull" $ | quote }}
          command: ['sh', '-c', "until nc -z {{ printf "%s %v" (include "groundx.search.baseDomain" $) (include "groundx.search.port" $) }}; do echo waiting for search; sleep 2; done"]
{{- end }}
{{- if hasKey $dpnd "db" }}
        - name: wait-for-database
          image: {{ include "groundx.busybox.image" $ }}
          imagePullPolicy: {{ include "groundx.busybox.pull" $ | quote }}
          command: ['sh', '-c', "until nc -z {{ printf "%s %v" (include "groundx.db.ro" $) (include "groundx.db.port" $) }}; do echo waiting for database; sleep 2; done"]
{{- end }}
{{- if hasKey $dpnd "stream" }}
        - name: wait-for-stream
          image: {{ include "groundx.busybox.image" $ }}
          imagePullPolicy: {{ include "groundx.busybox.pull" $ | quote }}
          command: ['sh', '-c', "until nc -z {{ printf "%s %v" (include "groundx.stream.domain" $) (include "groundx.stream.port" $) }}; do echo waiting for stream; sleep 2; done"]
{{- end }}
{{- end }}
      containers:
        - name: {{ $svc | quote }}
          image: {{ $image | quote }}
          imagePullPolicy: {{ $pull | quote }}
{{- if gt (len $scr) 0 }}
          envFrom:
{{- range $kk, $vv := $scr }}
            - secretRef:
                name: {{ $vv }}
{{- end }}
{{- end }}
          ports:
            - containerPort: {{ $cport }}
              protocol: TCP
{{ include "groundx.renderSecurityContext" (dict "ctx" $csct "indent" 10 "root" $ "user" $username "cfg" "container") }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ $cport }}
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: {{ $cport }}
            initialDelaySeconds: 10
            periodSeconds: 30
{{ include "groundx.renderContainerResources" (dict "ctx" $rs "indent" 10) }}
          volumeMounts:
            - name: config-volume
              mountPath: /home/{{ include "groundx.golang.home" $ }}/.cashbot/config.yaml
              subPath: config.yaml
      volumes:
        - name: config-volume
          configMap:
            name: config-yaml-map

{{- if $int }}
{{ include "groundx.renderInterface" (dict "name" $svc "lb" $int "root" $) }}
{{- end }}

{{ end }}
