licenseKey: "00000000-0000-0000-0000-000000000000"

admin:
  apiKey: "00000000-0000-0000-0000-000000000000"
  email: "support@mycorp.net"
  password: "password"
  username: "00000000-0000-0000-0000-000000000000"

cluster:
  pvClass: eyelevel-pv
  type: eks

serviceAccount:
  name: existing-service-account

cache:
  metrics:
    enabled: false

  existing:
    addr: X.X.X.use2.cache.amazonaws.com
    isCluster: true
    port: 6379
    ssl: true

db:
  username: eyelevel
  password: password

  # used to initialize DB
  # creates service user, db, and tables
  privilegedUsername: root
  privilegedPassword: password

  existing:
    ro: X.X.us-east-2.rds.amazonaws.com
    rw: X.X.us-east-2.rds.amazonaws.com
    port: 3306

file:
  bucketName: eyelevel

  existing:
    url: https://X.s3.us-west-2.amazonaws.com
    serviceType: s3

search:
  username: eyelevel
  password: R0otb_*t!kazs
  privilegedUsername: admin
  privilegedPassword: R0otb_*t!kazs

  existing:
    url: https://X.us-east-2.es.amazonaws.com

stream:
  enabled: false

  topics:
    preProcess:
      type: sqs
      url: https://sqs.us-east-2.amazonaws.com/X/file-pre-process
    process:
      type: sqs
      url: https://sqs.us-east-2.amazonaws.com/X/file-process
    summary:
      type: sqs
      url: https://sqs.us-east-2.amazonaws.com/X/file-summary
    update:
      type: sqs
      url: https://sqs.us-east-2.amazonaws.com/X/file-update
    upload:
      type: sqs
      url: https://sqs.us-east-2.amazonaws.com/X/file-upload
