apiVersion: v2
appVersion: 0.2.0
description: 'GroundX RAG on Prem: Secure, Accurate, Scaled'
home: https://www.eyelevel.ai/
maintainers:
- email: developer@groundx.ai
  name: GroundX Project Maintainers
name: groundx
sources:
- https://github.com/eyelevelai/groundx-on-prem
version: 0.2.0
